### ISSUE TITLE
DBFFieldType.cs double

### ISSUE THREAD

**Issue by monty241** [ekonbenefits/dotnetdbf#29]
In DBFFieldType.cs it reads:

`Binary = (byte) 0x42, //B in ASCII`

It seems however that B is (yet another) double format for Visual FoxPro. Maybe that is intended in the C# code, but if so it would be handy to add some comment.

**Comment by jbtule** [comment]
So I think this came from http://www.dbase.com/Knowledgebase/INT/db7_file_fmt.htm
And it's described as a binary memo file. Which I've never seen in the wild.

I'm generally not partial to adding VFP features, because we use this for Clipper, but I don't know if I care if the added feature doesn't interfere. I can see VFP uses B for Double
https://docs.microsoft.com/en-us/sql/odbc/microsoft/visual-foxpro-field-data-types?view=sql-server-ver15

**Comment by monty241** [comment]
It is actually intensively used by an accounting package named "Visma AccountView" for amounts and quantities. FoxPro indeed.

**Comment by monty241** [comment]
Attaching two test files, displaying the FoxPro types (1 row).

[General.zip](https://github.com/ekonbenefits/dotnetdbf/files/3847757/General.zip)

Could not easily integrate into test cases.

**Comment by monty241** [comment]
Alternative solution would be to keep it to Clipper (dBASE 3/4) by removing the FoxPro DbfFieldTypes and returning the binary value for unsupported field types instead of DbNull. That enables a consumer to interpret the additional field values based upon their type. 

Would that be a better suited option for you?

**Comment by jbtule** [comment]
Yeah, I'd be fine with that.

**Comment by monty241** [comment]
Ok, we will follow that approach and create new PR with some documentation.

**Comment by jbtule** [comment]
Thanks for the pull request. deployed in v6.0.0.3
